In [2]:
import pandas as pd
lst=['hello','my','name','is','shreyansh']
df=pd.DataFrame(lst)
print(df)

           0
0      hello
1         my
2       name
3         is
4  shreyansh


In [3]:
import pandas as pd

In [4]:
data={'Name':['Tom','nick','krish','jack'],
      'Age':[20,21,19,18]}
df=pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [5]:
import statistics
import numpy as np

numbers = [10, 20, 30, 40, 50, 20]

mean_value = statistics.mean(numbers)
median_value = statistics.median(numbers)
mode_value = statistics.mode(numbers)
variance_value = statistics.variance(numbers)
std_deviation = statistics.stdev(numbers)

print(mean_value)
print(median_value)
print(mode_value)
print(variance_value)
print(std_deviation)

28.333333333333332
25.0
20
216.66666666666666
14.719601443879744


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

reshaped = arr.reshape(2, 3)
print(reshaped)

multiplied = arr * 2
print(multiplied)

21
3.5
6
1
[[1 2 3]
 [4 5 6]]
[ 2  4  6  8 10 12]


In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)
print(A - B)
print(np.dot(A, B))
print(A.T)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [8]:
import numpy as np

random_array = np.random.rand(10)

print(random_array)
print(np.mean(random_array))
print(np.std(random_array))
print(np.min(random_array))
print(np.max(random_array))

[0.99093685 0.56856036 0.01114897 0.93095297 0.23057321 0.72065829
 0.14623694 0.70577748 0.1076752  0.23674642]
0.46492666822180995
0.3420685120618114
0.011148968748741717
0.9909368472958981


In [9]:
from scipy import stats
import numpy as np

data = [10, 12, 9, 11, 10, 13, 12]

mean_value = stats.tmean(data)
print(mean_value)

t_stat, p_value = stats.ttest_1samp(data, 10)
print(t_stat)
print(p_value)

11.0
1.8708286933869707
0.1105517404022668


In [10]:
from scipy import optimize
import numpy as np

f = lambda x: x**2 + 4*x + 4

result = optimize.minimize(f, 0)

print(result.x)
print(result.fun)

[-2.00000002]
0.0


In [12]:
import pandas as pd

data = {
    'name': ['alpha', 'beta', 'gamma', 'delta'],
    'age': [27, 28, 29, 25],
    'address': ['delhi', 'mumbai', 'lucknow', 'noida'],
    'qualification': ['msc', 'ma', 'mca', 'phd']
}

df = pd.DataFrame(data)

print(df[['name', 'qualification']])

    name qualification
0  alpha           msc
1   beta            ma
2  gamma           mca
3  delta           phd


In [17]:
import pandas as pd

data = pd.read_csv("/content/nba.csv", index_col="name")


first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]

print(first, "\n\n\n", second)

KeyError: 'Avery Bradley'